name: Development Build

on:
  workflow_dispatch:
  push:
    branches:
      - development

jobs:
  development_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: JDK Setup
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build Development
      run: mvn -B package --file pom.xml
