name: Pull Request Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - development

jobs:
  pull_request_build:
    runs_on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: JDK Setup
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build Pull Request
      run: mvn -B package --file pom.xml
